apiVersion: apps/v1
kind: Deployment
metadata:
  name: uitests
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uitests
  template:
    metadata:
      labels:
        app: uitests
    spec:
      containers:
      - name: uitests
        image: houssemdocker/seleniumtests:1.1
        resources:
          limits:
            memory: "200Mi"
            cpu: ".5"
